default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20

development:
  <<: *default
  database: fancyengine_development
  host: localhost

test:
  <<: *default
  database: fancyengine_test
  host: localhost
